# Generated by Django 4.1.5 on 2024-06-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0006_comment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "1 star"),
                    (2, "2 stars"),
                    (3, "3 stars"),
                    (4, "4 stars"),
                    (5, "5 stars"),
                ],
                default=5,
            ),
            preserve_default=False,
        ),
    ]
